// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://httuvgpexspyhxlapdgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0dHV2Z3BleHNweWh4bGFwZGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjQ3ODksImV4cCI6MjA3MjkwMDc4OX0.FDV9QiCvwKT0fLFyB9KbesmISF_vmYre_C4b5-FZg7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});